version: '3.7'
services:
  db_postgres:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=eureciclo
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=rny9He^pyN
    ports:
      - "5432:5432"
    networks:
      - postgres_django

  web:
    image: eureciclo
    depends_on:
      - migration
    working_dir: /code/eureciclo
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    networks:
      - postgres_django

  migration:
    build: .
    image: eureciclo
    working_dir: /code/eureciclo
    command: python manage.py migrate
    volumes:
        - .:/code
    networks:
      - postgres_django
    depends_on:
      - db_postgres

  teste:
    build: .
    image: eureciclo
    working_dir: /code/eureciclo
    command: python manage.py test
    volumes:
      - .:/code
    networks:
      - postgres_django
    depends_on:
      - migration

networks:
  postgres_django:
    driver: bridge
