version: '3.7'
services:
  db_postgres:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=eureciclo
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=rny9He^pyN
    ports:
      - "5432:5432"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
