# Generated by Django 3.2.12 on 2022-02-16 00:47

from django.db import migrations, models
import django.db.models.deletion
import upload_file.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('file', models.FileField(upload_to='uploads', validators=[upload_file.models.UploadFields.validate_file])),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FieldsFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('amounts', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('supplier', models.CharField(max_length=100)),
                ('upload_fields', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='upload_fields', to='upload_file.uploadfields')),
            ],
        ),
    ]
